### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by Epoche-Napoleon** [bihor/backendtools#2]
Installing via Composer with following Error message:
  [ UnexpectedValueException ]                                                 
  The package "backendtools" depends on "typo3db_legacy" which is not present  
   in the system.

**Comment by bihor** [comment]
I don know. Maybe it was the version-tag?
Can you test it again with version 1.4.1?

**Comment by bihor** [comment]
I guess it works now:

composer validate
./composer.json is valid
