### ISSUE TITLE
redirect check for sysfolder target pages

### ISSUE THREAD

**Issue by josefglatz** [bihor/backendtools#5]
Would it be possible to also show errors like if a redirect targets to a sys folder?

**Comment by bihor** [comment]
OK, implemented in version 4.3.0

**Comment by josefglatz** [comment]
Wow thank you very much!Diese Nachricht wurde von meinem Smartphone versandtAm 20.01.2023 um 16:10 schrieb Kurt Gusbeth ***@***.***>:﻿
Closed #5 as completed.
